const fs = require('fs');
let html = fs.readFileSync('convidado.html', 'utf8');

// 1. Regex to extract the full blocks of each misplaced syllabus-content
const regexEspecialistas = /<div class="syllabus-content"\s+id="especialistas">[\s\S]*?(?=<\div class="syllabus-content"|<\/section>|<div class="syllabus-tabs">|<section|<footer)/g;
const regexIa = /<div class="syllabus-content"\s+id="ia">[\s\S]*?(?=<\div class="syllabus-content"|<\/section>|<div class="syllabus-tabs">|<section|<footer)/g;
const regexLives = /<div class="syllabus-content"\s+id="lives">[\s\S]*?(?=<\div class="syllabus-content"|<\/section>|<div class="syllabus-tabs">|<section|<footer)/g;

let especialistasBlock = '';
let iaBlock = '';
let livesBlock = '';

html = html.replace(regexEspecialistas, (match) => {
    especialistasBlock = match;
    return '';
});

html = html.replace(regexIa, (match) => {
    iaBlock = match;
    return '';
});

html = html.replace(regexLives, (match) => {
    livesBlock = match;
    return '';
});

// Since the previous regex might have missed the closing </div> of each block if it was greedy or if the lookahead matched early, 
// let's do a more robust string manipulation: we know exactly where they start and what they contain because they were generated by our script.
// But wait, it's safer to just extract them using robust AST or indexOf.

let contentToInject = '';
if (especialistasBlock) contentToInject += especialistasBlock + '\n</div>\n';
if (iaBlock) contentToInject += iaBlock + '\n</div>\n';
if (livesBlock) contentToInject += livesBlock + '\n</div>\n';

// Let's actually rebuild them from data to be 100% sure they are perfect and have no unclosed divs.
